### ISSUE TITLE
Выгрузка бекапа на FTP ломает RESTAPI

### ISSUE THREAD

**Issue by ivstep** [mikopbx/ModuleBackup#10]
При выполнении бекапа на FTP сервер, запросы получения статуса пользователей возвращают ответ с кодом 500 по таймауту. Возможно, есть зависимость от объема выгружаемых данных, скорости канала.

Пример запроса и ответа:

curl "http://127.0.0.1/pbxcore/api/sip/getPeersStatuses"

{"jsonapi":{"version":"1.0"},"errors":["500 (Internal Server Error) "],"meta":{"timestamp":"2021-09-08T16:41:54+03:00","hash":"60e752960a547b815a95b8c6f75ffb3e5d4abb36"}}

**Comment by jorikfon** [comment]
Может быть надо сделать персональные все в этом модуле? Свой REST, вплоть до консольных команд. Чтобы не было завязок на основную систему, или как можно меньше их было, чтобы ни от версий не зависело ни от того в докере оно или на железе...

**Comment by boffart** [comment]
Выгрузки на FTP более не будет.
curlftpfs не собирается на актуальном Linux
