### ISSUE TITLE
Не удалось создать бекап на FTP

### ISSUE THREAD

**Issue by alexinc-2000** [mikopbx/ModuleBackup#16]
При попытке бекапа выдает ошибку:
Oct 29 13:15:03 daemon.err php.backend[10798]:  Failed to mount backup disk... on Backup
Локально бекапы создаются.

**Comment by boffart** [comment]
В Linux, последняя версия curlftpfs работала не корректна. 
Понизил версию до **curlftpfs-0.9.1** (она была в предыдущих версиях MikoPBX)

Ошибка будет исправлена в 2021.4.1+
