### ISSUE TITLE
Модуль резервного копирования не сохраняет настройки порта

### ISSUE THREAD

**Issue by Va-Bank** [mikopbx/ModuleBackup#27]
MIKOPBX ver: 2022.1.99, Модуль резервного копирования (Версия 1.55). В настройках расписания не запоминает порт. Прописываем порт SFTP, например, 44422, жмем сохранить. Открываем настройки, а там снова 22.
Но не проверяли пока как это работает в перспективе. Вдруг порт все таки сохраняется, просто при заходе в настройки поле порт не получает значение из конфига, а проставляется по-умолчанию? Обновились только сегодня. Завтра отпишусь сделается ли автоматический бекап

**Comment by Va-Bank** [comment]
Бекап по расписанию делается. Отсюда вывод. При заходе в Расписание архивации поле Порт просто не подхватывает номер порта из конфигурации и подставляет по-умолчанию - 22

**Comment by boffart** [comment]
Это баг отображения в web интерфейсе. 
Настройки сохраняются успешно.

**Comment by boffart** [comment]
Поправил. См. последний изменения [тут](https://github.com/mikopbx/ModuleBackup/issues/27).
