### ISSUE TITLE
Сортировка списка бекапов по дате. Формат даты 

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleBackup#30]
Подскажите, а когда исправят сортировку в модуле резервного копирования? Из релиза в релиз какая-то дичь. Может сделаете формат YYYY-MM-DD ?

https://t.me/mikopbx_dev/6301

**Comment by Va-Bank** [comment]
MIKOPBX ver: 2022.3.15
Модуль резервного копирования версии 1.75
Я щелкнул ЛКМ по заголовку "Дата архива". На скриншоте видно стрелку справа. Но сортировка все равно хромает. Декабрь и октябрь оказываются между ноябрем, ну и т.п.
![image](https://user-images.githubusercontent.com/4588055/206438940-126c0df9-b2ea-44d2-a266-b2fde8832b0b.png)
Настроено расписание архивации на сторонний сервер по SFTP. Локально только два архива присутствуют.
```
~# ls -l /storage/usbdisk1/mikopbx/backup/
total 8
drwxr-xr-x 3 www www 4096 Aug 25 12:22 763363328-backup_1661418629
drwxr-xr-x 3 www www 4096 Oct 11 14:26 backup_1665487603
~#
```
На удаленном сервере это выглядит так
![image](https://user-images.githubusercontent.com/4588055/206439487-0e542992-21ba-4cb4-93dd-57caf5efe4b1.png)

**Comment by boffart** [comment]
Вы приложите вывод "/storage/usbdisk1/mikopbx/backup/" с удаленного сервера (путь задается в настройках модуля). 
Не перепечатывать ведь со скрина.
