### ISSUE TITLE
Не работают бэкапы в docker

### ISSUE THREAD

**Issue by kernel21** [mikopbx/ModuleBackup#36]
При создании бэкапа в docker размер бэкапа 0, в логе системном ошибка
`php.backend[7369]:  Return value of Modules\ModuleBackup\Lib\Backup::getDockerHdd() must be of the type array, null returned on Modules\ModuleBackup\Lib\WorkerBackup_EXCEPTION`

**Comment by boffart** [comment]
а что у вас возвращает команда 
`df -k /storage`
приведите пример как вы запускаете контейнер.

**Comment by kernel21** [comment]
![Снимок экрана от 2023-06-29 20-12-16](https://github.com/mikopbx/ModuleBackup/assets/11707208/e46ac0f8-e69d-489c-83ed-2250338f7dc8)
Вывод команды во вложении.
Запускаю вот так:
`docker run --cap-add=NET_ADMIN --net=host --privileged --name mikopbx \
           -v /var/spool/mikopbx/cf:/cf \
           -v /var/spool/mikopbx/storage:/storage \
           -e SSH_PORT=23 \
           -e ID_WWW_USER="$(id -u www-data)" \
           -e ID_WWW_GROUP="$(id -g www-data)" \
           -it -d --restart always ghcr.io/mikopbx/mikopbx-x86-64`

**Comment by boffart** [comment]
приложите текст пожалуйста, тут копипаст нужен для анализа.

**Comment by kernel21** [comment]
`/ # df -k /storage
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/mikopbx-root
                     205309928   7394188 195802248   4% /cf`
Еше вывод mount прикоадываю
`/ # mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/WX7EKA2XLJ4JSAX2BKCLNSAFIG:/var/lib/docker/overlay2/l/ANO4DZ5HNYSPINOQIAFZVBVJXU,upperdir=/var/lib/docker/overlay2/3343cb525f7b0c2001f04ffc53b680709b2c137aea75ec82fb0176797bb6ca89/diff,workdir=/var/lib/docker/overlay2/3343cb525f7b0c2001f04ffc53b680709b2c137aea75ec82fb0176797bb6ca89/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k,inode64)
/dev/mapper/mikopbx-root on /cf type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/mikopbx-root on /storage type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/mikopbx-root on /etc/resolv.conf type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/mikopbx-root on /etc/hostname type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/mikopbx-root on /etc/hosts type ext4 (rw,relatime,errors=remount-ro)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
`

**Comment by kernel21** [comment]
Помогло, архив создается теперь не нулевого рамера. Но в браузере после создания идёт некая проверка, после которой во всплывающем окне выводится информация:
`DataTables warning: table id=existing-backup-files-table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`
В логе системном при этом тоже ошибки:
`Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Messages on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/App/Controllers on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/App/Forms on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/App/Views on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/App/Views on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/db on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/db on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/js/src on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/js/src on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/js on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/js on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/img on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/public/assets/css on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Setup on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Lib on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/custom_modules/ModuleUsersGroups/Lib on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/custom on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/custom on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/custom on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/custom on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/moh on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/moh on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/moh on Util
Jun 29 21:41:07 daemon.err php.backend[7194]:  Error on create folder /storage/usbdisk1/mikopbx/backup/backup_1688064062/mnt_point/storage/usbdisk1/mikopbx/media/moh on Util
`

**Comment by boffart** [comment]
По ошибке в web - проверьте в консоли  браузера, вероятно там тоже будет ошибка, мб она внесет ясность. 
По логам - не понятно. при создании бекапа не вышло создать каталоги, практически все они относятся к модулю "Группы пользователей".

**Comment by boffart** [comment]
Поправил в 1.84
