### ISSUE TITLE
Module deactivating

### ISSUE THREAD

**Issue by emassen** [mikopbx/ModuleBackup#39]
I can't get it in the logs, but every day ModuloBackup appears deactivated, I activate it and the next day it appears deactivated again. Where can I get the error LOG of why this is occurring?

**Comment by jorikfon** [comment]
What the PBX version do you use now?

**Comment by jorikfon** [comment]
Starting from version 2023.2, there is a new feature that disables a malfunctioning module if it is the cause of certain exceptions.
Do you see something in logs?

**Comment by emassen** [comment]
Latest version, 2023.2.206. The same behavior was occurring in the previous version too, I don't remember the version number, but it was the first in production. On Friday I upgraded to the latter and the problem continues. I'm looking at all types of logs, and it doesn't show me anything, does it have a specific log where the module error should record?

**Comment by jorikfon** [comment]
In the system/messages, try to search "error", "exception".
If you have no any secret data, you can attach screenshots and we will reproduce it on the test system.

**Comment by emassen** [comment]
It is not showing an error in the system/messages, prints, I don't know how it would be seen, the system currently hangs for almost 24 hours after being activated.

**Comment by emassen** [comment]
Sep 27 21:14:00 auth.warning MikoPBX[7894]:  File is not original: /usr/www/src//Common/Providers/WhoopsErrorHandlerProvider.php

**Comment by jorikfon** [comment]
> Sep 27 21:14:00 auth.warning MikoPBX[7894]: File is not original: /usr/www/src//Common/Providers/WhoopsErrorHandlerProvider.php

It is ok, cause you change system file. We are waiting for error in module Backup :)

**Comment by emassen** [comment]
Friend, I found the error, a command was placed internally within a backup file and that was causing the error. We can close this issue and thank you for your prompt service.

**Comment by jorikfon** [comment]
Nice!
