### ISSUE TITLE
Failed to mount backup disk... on Backup

### ISSUE THREAD

**Issue by Va-Bank** [mikopbx/ModuleBackup#44]
Произвел обновление с MIKOPBX ver: 2023.1.223 до MIKOPBX ver: 2024.1.114
Модуль резервного копирования был 1.77, стал 1.86
При попытке начать резервное копирование выходит ошибка в system/message:

**daemon.err php.backend[24108]:  Failed to mount backup disk... on Backup**

Естественно на предыдущей версии все работало. Удалил модуль БЕЗ сохранения настроек. Установил модуль заново. Все настроил. Но ошибка такая же. Мои настройки:

![Снимок](https://github.com/mikopbx/ModuleBackup/assets/4588055/bc018cef-837c-4e02-991b-98520bbc30a8)

**Comment by Madji47** [comment]
Jul 11 22:56:41 daemon.debug mount.davfs:  davfs2 1.6.1
Jul 11 22:56:41 daemon.debug mount.davfs:  davfs2 1.6.1
Jul 11 22:56:49 daemon.warning php.backend[2770]:  There is not enough free disk space. on Modules\ModuleBackup\Lib\Backup
Jul 11 22:59:46 daemon.err php.backend[4573]:  TypeError: Return value of Modules\ModuleBackup\Lib\Backup::remove() must be an instance of MikoPBX\PBXCoreREST\Lib\PBXApiResult, instance of Modules\ModuleBackup\Models\BackupRules returned in file /storage/usbdisk1/mikopbx/custom_modules/ModuleBackup/Lib/Backup.php on line 533
Jul 11 22:59:46 daemon.err php.backend[4573]:  Stack trace:
Jul 11 22:59:46 daemon.err php.backend[4573]:    1. TypeError->() /storage/usbdisk1/mikopbx/custom_modules/ModuleBackup/Lib/Backup.php:533
Jul 11 22:59:46 daemon.err php.backend[4573]:    2. Modules\ModuleBackup\Lib\Backup->remove() /storage/usbdisk1/mikopbx/custom_modules/ModuleBackup/Lib/BackupConf.php:80
Jul 11 22:59:46 daemon.err php.backend[4573]:    3. Modules\ModuleBackup\Lib\BackupConf->moduleRestAPICallback() /offload/rootfs/usr/www/src/PBXCoreREST/Lib/PbxExtensionsProcessor.php:90
Jul 11 22:59:46 daemon.err php.backend[4573]:    4. MikoPBX\PBXCoreREST\Lib\PbxExtensionsProcessor->callBack() /offload/rootfs/usr/www/src/PBXCoreREST/Workers/WorkerApiCommands.php:124
Jul 11 22:59:46 daemon.err php.backend[4573]:    5. MikoPBX\PBXCoreREST\Workers\WorkerApiCommands->prepareAnswer() /offload/rootfs/usr/www/src/Core/System/BeanstalkClient.php:369
Jul 11 22:59:46 daemon.err php.backend[4573]:    6. call_user_func() /offload/rootfs/usr/www/src/Core/System/BeanstalkClient.php:369
Jul 11 22:59:46 daemon.err php.backend[4573]:    7. MikoPBX\Core\System\BeanstalkClient->wait() /offload/rootfs/usr/www/src/PBXCoreREST/Workers/WorkerApiCommands.php:75
Jul 11 22:59:46 daemon.err php.backend[4573]:    8. MikoPBX\PBXCoreREST\Workers\WorkerApiCommands->start() /offload/rootfs/usr/www/src/Core/Workers/WorkerBase.php:151
Jul 11 22:59:46 daemon.err php.backend[4573]:    9. MikoPBX\Core\Workers\WorkerBase->startWorker() /offload/rootfs/usr/www/src/PBXCoreREST/Workers/WorkerApiCommands.php:210
Jul 11 22:59:46 daemon.err php.backend[4573]:   on MikoPBX\Common\Handlers\CriticalErrorsHandler::handleExceptionWithSyslog
Jul 11 23:00:04 daemon.warning php.backend[5186]:  There is not enough free disk space. on Modules\ModuleBackup\Lib\Backup
Jul 11

**Comment by boffart** [comment]
для корректного создания локальных резервных копий нужен патч для MikoPBX
https://github.com/mikopbx/Core/commit/a9b4361c3b91120676d5e5941f681ca9b766bf6a
